// Fill in  your WiFi networks SSID and password
#define SECRET_SSID "AndroidHotspot5016"
#define SECRET_PASS "83942512"

// Fill in the hostname of your AWS IoT broker
#define SECRET_BROKER "a2uezkpet17x86-ats.iot.ap-northeast-2.amazonaws.com"

// Fill in the boards public certificate
const char SECRET_CERTIFICATE[] = R"(
-----BEGIN CERTIFICATE-----
MIICiTCCAXGgAwIBAgIVANs4xlSwtL4E+InRqmbtYO4lQxPcMA0GCSqGSIb3DQEB
CwUAME0xSzBJBgNVBAsMQkFtYXpvbiBXZWIgU2VydmljZXMgTz1BbWF6b24uY29t
IEluYy4gTD1TZWF0dGxlIFNUPVdhc2hpbmd0b24gQz1VUzAeFw0yMTEwMjgxNTI5
MDZaFw00OTEyMzEyMzU5NTlaMBgxFjAUBgNVBAMTDU15TUtSV2lGaTEwMTAwWTAT
BgcqhkjOPQIBBggqhkjOPQMBBwNCAATjhQCQ2gvBz7h+aiD0n+ZIc6v0ZBaxqJ31
S749Cr7oh6StYwdtaQD2liVkBMH/X+4dNw7/JxbHAGYfcy3cQyOho2AwXjAfBgNV
HSMEGDAWgBTPRe2ZZKMA6Z7TvEBSmgS34RSEJzAdBgNVHQ4EFgQUxgO1W9A/RsQe
oz6hzzr7tY/ceD0wDAYDVR0TAQH/BAIwADAOBgNVHQ8BAf8EBAMCB4AwDQYJKoZI
hvcNAQELBQADggEBAAw4nfSKeC5TWiTNhtR+Yu369LqQ1KTXHxA7KZJqAXB3gP4D
rUshwARdjfFyyEf91NeNyAiUh1JW+xwDKsigK1DtlAFzTpyLJeTbRGnZAdvsYoPU
1vu6/1C4U0j87EOxCLSwy5bqDK8PSvkykpS+7yqShKn/P5Rk7g4WHcBMzKpIEnQy
XRcxYxHR+smoIs6/a2r2ZSk6LBTALSANfbxGAZZN0uWNbQbzm+/+K4XJFZUT2vYp
vfSBk3aybMmwK4imrZtvAIv2gPR5PJ6XQtW1VpzwmNu7SIeOhdqHcUncV2hmHMu1
ZLjJpPAyHaIxRflEjY2jIX8BqzVEyreuqvhrn8s=
-----END CERTIFICATE-----
)";
